#!/usr/bin/env python3
"""Generate zones.js (IANA zone -> [lat, lon, country code] plus country names) from tzdata's zone.tab and iso3166.tab."""
import json, os, re, sys

src = sys.argv[1] if len(sys.argv) > 1 else "/usr/share/zoneinfo/zone.tab"
iso = os.path.join(os.path.dirname(src), "iso3166.tab")

def dms(s, deg_digits):
    sign = -1 if s[0] == "-" else 1
    s = s[1:]
    d, m, sec = int(s[:deg_digits]), int(s[deg_digits:deg_digits + 2]), int(s[deg_digits + 2:] or 0)
    return round(sign * (d + m / 60 + sec / 3600), 3)

zones = {}
for line in open(src, encoding="utf-8"):
    if line.startswith("#") or not line.strip():
        continue
    cc, coord, zone = line.split("\t")[:3]
    lat, lon = re.match(r"([+-]\d+)([+-]\d+)", coord).groups()
    zones[zone.strip()] = [dms(lat, 2), dms(lon, 3), cc]

countries = {}
for line in open(iso, encoding="utf-8"):
    if line.startswith("#") or not line.strip():
        continue
    cc, name = line.rstrip("\n").split("\t")[:2]
    countries[cc] = name

with open("zones.js", "w") as f:
    f.write("// Generated by scripts/build_zones.py from tzdata zone.tab + iso3166.tab\n")
    f.write("window.ZONE_COORDS = " + json.dumps(dict(sorted(zones.items())), separators=(",", ":")) + ";\n")
    f.write("window.COUNTRY_NAMES = " + json.dumps(dict(sorted(countries.items())), separators=(",", ":"), ensure_ascii=False) + ";\n")
print(f"{len(zones)} zones")
