#!/usr/bin/env python3
"""Generate zones.js (IANA zone -> [lat, lon]) from tzdata's zone.tab."""
import json, re, sys

src = sys.argv[1] if len(sys.argv) > 1 else "/usr/share/zoneinfo/zone.tab"

def dms(s, deg_digits):
    sign = -1 if s[0] == "-" else 1
    s = s[1:]
    d, m, sec = int(s[:deg_digits]), int(s[deg_digits:deg_digits + 2]), int(s[deg_digits + 2:] or 0)
    return round(sign * (d + m / 60 + sec / 3600), 3)

zones = {}
for line in open(src, encoding="utf-8"):
    if line.startswith("#") or not line.strip():
        continue
    _, coord, zone = line.split("\t")[:3]
    lat, lon = re.match(r"([+-]\d+)([+-]\d+)", coord).groups()
    zones[zone.strip()] = [dms(lat, 2), dms(lon, 3)]

with open("zones.js", "w") as f:
    f.write("// Generated by scripts/build_zones.py from tzdata zone.tab\n")
    f.write("window.ZONE_COORDS = " + json.dumps(dict(sorted(zones.items())), separators=(",", ":")) + ";\n")
print(f"{len(zones)} zones")
